import { saveAs } from 'file-saver'
import { loadCompanyLogoImage, type ExportCompanyHeader } from './excelExport'

export type FinanceExportLanguage = 'en' | 'pt' | 'bi'

export type FinanceExportCompany = ExportCompanyHeader

export type FinanceExportCounterparty = {
  kind: 'customer' | 'supplier'
  name: string
  code?: string | null
  taxId?: string | null
  contactName?: string | null
  email?: string | null
  phone?: string | null
  address?: string | null
  source: 'document_snapshot' | 'master'
}

export type FinanceExportBank = {
  name: string
  bankName?: string | null
  maskedAccountNumber?: string | null
  operatingCurrency?: string | null
  swift?: string | null
  nib?: string | null
}

export type FinanceExportContext = {
  title: string
  subtitle?: string
  language: FinanceExportLanguage
  generatedAt: string
  generatedBy?: string | null
  company: FinanceExportCompany
  counterparty?: FinanceExportCounterparty | null
  counterpartyScope?: string | null
  bank?: FinanceExportBank | null
  period?: { from?: string | null; to?: string | null }
  filters?: string[]
  baseCurrency: string
  disclaimer?: string | null
}

export type FinanceExportCell = string | number | boolean | null | undefined

export type FinanceExportColumn = {
  key: string
  label: string
  type?: 'text' | 'number' | 'currency' | 'date' | 'status'
  width?: number
}

export type FinanceExportSummaryItem = {
  label: string
  value: FinanceExportCell
  type?: 'text' | 'number' | 'currency'
}

export type FinanceExportSection = {
  title: string
  columns: FinanceExportColumn[]
  rows: Array<Record<string, FinanceExportCell>>
  totals?: Array<Record<string, FinanceExportCell>>
}

export type FinanceExportModel = {
  filename: string
  context: FinanceExportContext
  summary?: FinanceExportSummaryItem[]
  sections: FinanceExportSection[]
  orientation?: 'portrait' | 'landscape'
}

type FinanceExportCopy = {
  company: string
  counterparty: string
  customer: string
  supplier: string
  counterpartyScope: string
  bankAccount: string
  generated: string
  generatedBy: string
  period: string
  filters: string
  baseCurrency: string
  source: string
  page: string
  of: string
  total: string
}

const WISECORE_DARK_TEAL = 'FF014558'
const WISECORE_MID_TEAL = 'FF009679'
const NEUTRAL_TEXT = 'FF111827'
const MUTED_TEXT = 'FF4B5563'
const LIGHT_BORDER = 'FFD1D5DB'
const LIGHT_FILL = 'FFF3F4F6'

export function financeExportCopy(language: FinanceExportLanguage): FinanceExportCopy {
  const portuguese = {
    company: 'Empresa',
    counterparty: 'Contraparte',
    customer: 'Cliente',
    supplier: 'Fornecedor',
    counterpartyScope: 'Âmbito da contraparte',
    bankAccount: 'Conta bancária',
    generated: 'Gerado em',
    generatedBy: 'Gerado por',
    period: 'Período',
    filters: 'Filtros',
    baseCurrency: 'Moeda base da empresa',
    source: 'Fonte',
    page: 'Página',
    of: 'de',
    total: 'Total',
  }
  if (language === 'pt') return portuguese
  if (language === 'bi') {
    return {
      company: 'Empresa / Company',
      counterparty: 'Contraparte / Counterparty',
      customer: 'Cliente / Customer',
      supplier: 'Fornecedor / Supplier',
      counterpartyScope: 'Âmbito / Scope',
      bankAccount: 'Conta bancária / Bank account',
      generated: 'Gerado em / Generated',
      generatedBy: 'Gerado por / Generated by',
      period: 'Período / Period',
      filters: 'Filtros / Filters',
      baseCurrency: 'Moeda base / Base currency',
      source: 'Fonte / Source',
      page: 'Página / Page',
      of: 'de / of',
      total: 'Total',
    }
  }
  return {
    company: 'Company',
    counterparty: 'Counterparty',
    customer: 'Customer',
    supplier: 'Supplier',
    counterpartyScope: 'Counterparty scope',
    bankAccount: 'Bank account',
    generated: 'Generated',
    generatedBy: 'Generated by',
    period: 'Period',
    filters: 'Filters',
    baseCurrency: 'Company base currency',
    source: 'Source',
    page: 'Page',
    of: 'of',
    total: 'Total',
  }
}

export function sanitizeFinanceFilename(value: string) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, '-')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^-+|-+$/g, '')
    .slice(0, 150)
}

function financeWorksheetName(title: string, index: number, usedNames: Set<string>) {
  const fallback = `Sheet ${index + 1}`
  const base = title
    .replace(/[*?:/\\[\]]/g, ' - ')
    .replace(/\s+/g, ' ')
    .replace(/^'+|'+$/g, '')
    .trim() || fallback
  let candidate = base.slice(0, 31)
  let duplicate = 2
  while (usedNames.has(candidate.toLowerCase())) {
    const suffix = ` ${duplicate}`
    candidate = `${base.slice(0, Math.max(1, 31 - suffix.length))}${suffix}`
    duplicate += 1
  }
  usedNames.add(candidate.toLowerCase())
  return candidate
}

export function maskFinanceAccountNumber(value?: string | null) {
  const normalized = String(value || '').replace(/\s+/g, '').trim()
  if (!normalized) return null
  if (normalized.length <= 4) return `•••• ${normalized}`
  return `•••• ${normalized.slice(-4)}`
}

function cleanParts(parts: Array<string | null | undefined>, separator = ' | ') {
  return parts.map((part) => String(part || '').trim()).filter(Boolean).join(separator)
}

function companyLines(company: FinanceExportCompany) {
  return [
    cleanParts([company.companyName, company.legalName && company.legalName !== company.companyName ? company.legalName : null], ' — '),
    cleanParts([
      company.taxId ? `NUIT: ${company.taxId}` : null,
      company.email,
      company.phone,
    ]),
    company.address || '',
  ].filter(Boolean)
}

function counterpartyLines(counterparty: FinanceExportCounterparty) {
  return [
    cleanParts([counterparty.name, counterparty.code ? `(${counterparty.code})` : null], ' '),
    cleanParts([
      counterparty.taxId ? `NUIT: ${counterparty.taxId}` : null,
      counterparty.contactName,
      counterparty.email,
      counterparty.phone,
    ]),
    counterparty.address || '',
  ].filter(Boolean)
}

function bankLines(bank: FinanceExportBank) {
  return [
    cleanParts([bank.name, bank.bankName]),
    cleanParts([
      bank.maskedAccountNumber,
      bank.operatingCurrency,
      bank.swift ? `SWIFT: ${bank.swift}` : null,
      bank.nib ? `NIB: ${bank.nib}` : null,
    ]),
  ].filter(Boolean)
}

function contextLines(context: FinanceExportContext, copy: FinanceExportCopy) {
  const lines: string[] = []
  lines.push(`${copy.generated}: ${new Date(context.generatedAt).toLocaleString()}`)
  if (context.generatedBy) lines.push(`${copy.generatedBy}: ${context.generatedBy}`)
  lines.push(`${copy.baseCurrency}: ${context.baseCurrency}`)
  if (context.period?.from || context.period?.to) {
    lines.push(`${copy.period}: ${context.period.from || '—'} — ${context.period.to || '—'}`)
  }
  if (context.filters?.length) lines.push(`${copy.filters}: ${context.filters.join(' | ')}`)
  return lines
}

function excelAlignment(type?: FinanceExportColumn['type']) {
  return {
    vertical: 'top',
    horizontal: type === 'currency' || type === 'number' ? 'right' : 'left',
    wrapText: true,
  } as const
}

function applyExcelHeaderCell(cell: import('exceljs').Cell, value: FinanceExportCell) {
  cell.value = value
  cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: WISECORE_DARK_TEAL } }
  cell.border = {
    top: { style: 'thin', color: { argb: WISECORE_MID_TEAL } },
    left: { style: 'thin', color: { argb: WISECORE_MID_TEAL } },
    bottom: { style: 'thin', color: { argb: WISECORE_MID_TEAL } },
    right: { style: 'thin', color: { argb: WISECORE_MID_TEAL } },
  }
  cell.alignment = { vertical: 'middle', wrapText: true }
}

export async function exportFinanceExcel(model: FinanceExportModel) {
  const ExcelJS = await import('exceljs')
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'StockWise'
  workbook.created = new Date(model.context.generatedAt)
  workbook.modified = new Date(model.context.generatedAt)

  const copy = financeExportCopy(model.context.language)
  const logo = await loadCompanyLogoImage(model.context.company.logoUrl)
  const sections = model.sections.length ? model.sections : [{
    title: model.context.title,
    columns: [] as FinanceExportColumn[],
    rows: [] as Array<Record<string, FinanceExportCell>>,
  }]
  const worksheetNames = new Set<string>()

  sections.forEach((section, sectionIndex) => {
    const sheet = workbook.addWorksheet(financeWorksheetName(section.title, sectionIndex, worksheetNames), {
      properties: { defaultRowHeight: 20 },
      views: [{ showGridLines: false }],
      pageSetup: {
        orientation: model.orientation || 'landscape',
        paperSize: 9,
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        margins: { left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
      },
    })

    const totalColumns = Math.max(section.columns.length, 2)
    sheet.columns = Array.from({ length: totalColumns }, (_, index) => ({
      width: section.columns[index]?.width || 18,
    }))
    const merge = (row: number, fromColumn = 1) => {
      if (fromColumn < totalColumns) sheet.mergeCells(row, fromColumn, row, totalColumns)
    }

    let rowNumber = 1
    let textColumn = 1
    if (logo) {
      const imageId = workbook.addImage(logo)
      sheet.addImage(imageId, {
        tl: { col: 0.1, row: 0.1 },
        ext: { width: 96, height: 56 },
      })
      sheet.getColumn(1).width = Math.max(sheet.getColumn(1).width || 14, 16)
      textColumn = 2
    }

    for (const [index, line] of companyLines(model.context.company).entries()) {
      merge(rowNumber, textColumn)
      const cell = sheet.getCell(rowNumber, textColumn)
      cell.value = line
      cell.font = index === 0
        ? { size: 16, bold: true, color: { argb: WISECORE_DARK_TEAL } }
        : { size: 10, color: { argb: MUTED_TEXT } }
      rowNumber += 1
    }
    rowNumber = Math.max(rowNumber + 1, 5)

    if (model.context.counterparty) {
      merge(rowNumber)
      const label = model.context.counterparty.kind === 'customer' ? copy.customer : copy.supplier
      sheet.getCell(rowNumber, 1).value = label
      sheet.getCell(rowNumber, 1).font = { bold: true, color: { argb: WISECORE_MID_TEAL } }
      rowNumber += 1
      for (const line of counterpartyLines(model.context.counterparty)) {
        merge(rowNumber)
        sheet.getCell(rowNumber, 1).value = line
        sheet.getCell(rowNumber, 1).font = { size: 10, color: { argb: NEUTRAL_TEXT } }
        rowNumber += 1
      }
      rowNumber += 1
    } else if (model.context.counterpartyScope) {
      merge(rowNumber)
      sheet.getCell(rowNumber, 1).value = `${copy.counterpartyScope}: ${model.context.counterpartyScope}`
      sheet.getCell(rowNumber, 1).font = { size: 10, color: { argb: MUTED_TEXT } }
      rowNumber += 2
    }

    if (model.context.bank) {
      merge(rowNumber)
      sheet.getCell(rowNumber, 1).value = copy.bankAccount
      sheet.getCell(rowNumber, 1).font = { bold: true, color: { argb: WISECORE_MID_TEAL } }
      rowNumber += 1
      for (const line of bankLines(model.context.bank)) {
        merge(rowNumber)
        sheet.getCell(rowNumber, 1).value = line
        sheet.getCell(rowNumber, 1).font = { size: 10, color: { argb: NEUTRAL_TEXT } }
        rowNumber += 1
      }
      rowNumber += 1
    }

    merge(rowNumber)
    const titleCell = sheet.getCell(rowNumber, 1)
    titleCell.value = model.context.title
    titleCell.font = { size: 15, bold: true, color: { argb: 'FFFFFFFF' } }
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: WISECORE_DARK_TEAL } }
    titleCell.alignment = { vertical: 'middle', wrapText: true }
    sheet.getRow(rowNumber).height = 26
    rowNumber += 1

    if (model.context.subtitle) {
      merge(rowNumber)
      sheet.getCell(rowNumber, 1).value = model.context.subtitle
      sheet.getCell(rowNumber, 1).font = { size: 10, color: { argb: MUTED_TEXT } }
      rowNumber += 1
    }
    for (const line of contextLines(model.context, copy)) {
      merge(rowNumber)
      sheet.getCell(rowNumber, 1).value = line
      sheet.getCell(rowNumber, 1).font = { size: 10, color: { argb: MUTED_TEXT } }
      rowNumber += 1
    }
    rowNumber += 1

    if (sectionIndex === 0 && model.summary?.length) {
      const summaryStart = rowNumber
      for (const item of model.summary) {
        sheet.getCell(rowNumber, 1).value = item.label
        sheet.getCell(rowNumber, 1).font = { bold: true, color: { argb: MUTED_TEXT } }
        sheet.getCell(rowNumber, 2).value = item.value ?? ''
        sheet.getCell(rowNumber, 2).font = { bold: true, color: { argb: NEUTRAL_TEXT } }
        if (item.type === 'currency' && typeof item.value === 'number') {
          sheet.getCell(rowNumber, 2).numFmt = '#,##0.00;[Red](#,##0.00)'
        }
        rowNumber += 1
      }
      for (let row = summaryStart; row < rowNumber; row += 1) {
        sheet.getCell(row, 1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT_FILL } }
        sheet.getCell(row, 2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT_FILL } }
      }
      rowNumber += 1
    }

    merge(rowNumber)
    sheet.getCell(rowNumber, 1).value = section.title
    sheet.getCell(rowNumber, 1).font = { size: 12, bold: true, color: { argb: WISECORE_DARK_TEAL } }
    rowNumber += 1

    const headerRowNumber = rowNumber
    section.columns.forEach((column, index) => {
      const cell = sheet.getCell(headerRowNumber, index + 1)
      applyExcelHeaderCell(cell, column.label)
      cell.alignment = excelAlignment(column.type)
    })
    rowNumber += 1

    const dataStart = rowNumber
    for (const [rowIndex, record] of section.rows.entries()) {
      section.columns.forEach((column, columnIndex) => {
        const cell = sheet.getCell(rowNumber, columnIndex + 1)
        const value = record[column.key]
        cell.value = value ?? ''
        cell.alignment = excelAlignment(column.type)
        cell.border = { bottom: { style: 'thin', color: { argb: LIGHT_BORDER } } }
        if (rowIndex % 2 === 1) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } }
        }
        if (typeof value === 'number') {
          cell.numFmt = column.type === 'currency'
            ? '#,##0.00;[Red](#,##0.00)'
            : '#,##0.00;[Red]-#,##0.00'
        }
      })
      rowNumber += 1
    }

    for (const total of section.totals || []) {
      section.columns.forEach((column, columnIndex) => {
        const cell = sheet.getCell(rowNumber, columnIndex + 1)
        const value = total[column.key]
        cell.value = value ?? ''
        cell.font = { bold: true, color: { argb: NEUTRAL_TEXT } }
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT_FILL } }
        cell.alignment = excelAlignment(column.type)
        if (typeof value === 'number') {
          cell.numFmt = column.type === 'currency'
            ? '#,##0.00;[Red](#,##0.00)'
            : '#,##0.00;[Red]-#,##0.00'
        }
      })
      rowNumber += 1
    }

    if (model.context.disclaimer || model.context.company.footerNote) {
      rowNumber += 1
      merge(rowNumber)
      const footer = [model.context.disclaimer, model.context.company.footerNote].filter(Boolean).join(' | ')
      sheet.getCell(rowNumber, 1).value = footer
      sheet.getCell(rowNumber, 1).font = { italic: true, size: 9, color: { argb: MUTED_TEXT } }
      sheet.getCell(rowNumber, 1).alignment = { wrapText: true, vertical: 'top' }
    }

    if (section.columns.length) {
      sheet.autoFilter = {
        from: { row: headerRowNumber, column: 1 },
        to: { row: headerRowNumber, column: section.columns.length },
      }
    }
    sheet.views = [{ state: 'frozen', ySplit: headerRowNumber, showGridLines: false }]
    sheet.pageSetup.printArea = `A1:${sheet.getColumn(totalColumns).letter}${Math.max(rowNumber, dataStart)}`
    sheet.pageSetup.printTitlesRow = `${headerRowNumber}:${headerRowNumber}`
    sheet.headerFooter.oddFooter = `&LStockWise&C${copy.page} &P ${copy.of} &N&R${model.context.baseCurrency}`
  })

  const buffer = await workbook.xlsx.writeBuffer()
  const filename = `${sanitizeFinanceFilename(model.filename.replace(/\.xlsx$/i, '')) || 'StockWise_Finance'}.xlsx`
  saveAs(new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  }), filename)
}

async function buildFinancePdf(model: FinanceExportModel) {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const orientation = model.orientation || 'landscape'
  const doc = new jsPDF({ orientation, unit: 'pt', format: 'a4' })
  const copy = financeExportCopy(model.context.language)
  const logo = await loadCompanyLogoImage(model.context.company.logoUrl)
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 36
  const contentRight = pageWidth - margin
  const headerPages = new Set<number>()

  const drawHeader = () => {
    headerPages.add(doc.getCurrentPageInfo().pageNumber)
    let y = 30
    let companyX = margin
    if (logo) {
      doc.addImage(logo.base64, logo.extension.toUpperCase(), margin, 24, 78, 44)
      companyX = 126
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(1, 69, 88)
    doc.text(companyLines(model.context.company)[0] || model.context.company.companyName, companyX, y)
    y += 13
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(75, 85, 99)
    for (const line of companyLines(model.context.company).slice(1)) {
      doc.text(line, companyX, y, { maxWidth: contentRight - companyX })
      y += 11
    }
    y = Math.max(y + 5, 78)

    if (model.context.counterparty) {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 150, 121)
      doc.text(model.context.counterparty.kind === 'customer' ? copy.customer : copy.supplier, margin, y)
      y += 11
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(17, 24, 39)
      for (const line of counterpartyLines(model.context.counterparty)) {
        doc.text(line, margin, y, { maxWidth: contentRight - margin })
        y += 11
      }
      y += 4
    } else if (model.context.counterpartyScope) {
      doc.setTextColor(75, 85, 99)
      doc.text(`${copy.counterpartyScope}: ${model.context.counterpartyScope}`, margin, y)
      y += 15
    }

    if (model.context.bank) {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 150, 121)
      doc.text(copy.bankAccount, margin, y)
      y += 11
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(17, 24, 39)
      for (const line of bankLines(model.context.bank)) {
        doc.text(line, margin, y, { maxWidth: contentRight - margin })
        y += 11
      }
      y += 4
    }

    doc.setFillColor(1, 69, 88)
    doc.rect(margin, y, contentRight - margin, 24, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(255, 255, 255)
    doc.text(model.context.title, margin + 8, y + 16, { maxWidth: contentRight - margin - 16 })
    y += 36

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(75, 85, 99)
    if (model.context.subtitle) {
      doc.text(model.context.subtitle, margin, y, { maxWidth: contentRight - margin })
      y += 12
    }
    for (const line of contextLines(model.context, copy)) {
      doc.text(line, margin, y, { maxWidth: contentRight - margin })
      y += 11
    }
    doc.setDrawColor(209, 213, 219)
    doc.line(margin, y + 2, contentRight, y + 2)
    return y + 12
  }

  let cursorY = drawHeader()
  const headerBottom = cursorY
  const ensureCurrentPageHeader = () => {
    const pageNumber = doc.getCurrentPageInfo().pageNumber
    if (!headerPages.has(pageNumber)) drawHeader()
  }

  if (model.summary?.length) {
    autoTable(doc, {
      startY: cursorY,
      margin: { left: margin, right: margin, top: headerBottom, bottom: 44 },
      body: model.summary.map((item) => [
        item.label,
        typeof item.value === 'number' && item.type === 'currency'
          ? `${model.context.baseCurrency} ${item.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
          : String(item.value ?? '—'),
      ]),
      theme: 'grid',
      styles: { fontSize: 8.5, cellPadding: 5, lineColor: [209, 213, 219] },
      columnStyles: { 0: { fontStyle: 'bold', fillColor: [243, 244, 246] }, 1: { halign: 'right' } },
      willDrawPage: () => {
        ensureCurrentPageHeader()
      },
    })
    cursorY = ((doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || cursorY) + 16
  }

  for (const section of model.sections) {
    if (cursorY > pageHeight - 96) {
      doc.addPage()
      cursorY = drawHeader()
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(1, 69, 88)
    doc.text(section.title, margin, cursorY)
    cursorY += 8
    const moneyColumns = new Set(
      section.columns
        .map((column, index) => column.type === 'currency' || column.type === 'number' ? index : -1)
        .filter((index) => index >= 0),
    )
    const body = [
      ...section.rows.map((row) => section.columns.map((column) => {
        const value = row[column.key]
        if (typeof value === 'number' && column.type === 'currency') {
          return `${model.context.baseCurrency} ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
        }
        if (typeof value === 'number') {
          return value.toLocaleString(undefined, { maximumFractionDigits: 2 })
        }
        return String(value ?? '—')
      })),
      ...(section.totals || []).map((row) => section.columns.map((column) => {
        const value = row[column.key]
        if (typeof value === 'number' && column.type === 'currency') {
          return `${model.context.baseCurrency} ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
        }
        return String(value ?? '')
      })),
    ]
    const totalStart = section.rows.length
    autoTable(doc, {
      startY: cursorY,
      margin: { left: margin, right: margin, top: headerBottom, bottom: 50 },
      head: [section.columns.map((column) => column.label)],
      body,
      theme: 'grid',
      styles: {
        fontSize: orientation === 'landscape' ? 7.5 : 8,
        cellPadding: 4,
        lineColor: [209, 213, 219],
        overflow: 'linebreak',
        textColor: [17, 24, 39],
      },
      headStyles: { fillColor: [1, 69, 88], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [249, 250, 251] },
      columnStyles: Object.fromEntries([...moneyColumns].map((index) => [index, { halign: 'right' }])),
      didParseCell: (data: { section: string; row: { index: number }; cell: { styles: { fontStyle: string; fillColor: [number, number, number] } } }) => {
        if (data.section === 'body' && data.row.index >= totalStart) {
          data.cell.styles.fontStyle = 'bold'
          data.cell.styles.fillColor = [243, 244, 246]
        }
      },
      willDrawPage: () => {
        ensureCurrentPageHeader()
      },
    })
    cursorY = ((doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || cursorY) + 18
  }

  const disclaimer = [model.context.disclaimer, model.context.company.footerNote].filter(Boolean).join(' | ')
  if (disclaimer) {
    const lines = doc.splitTextToSize(disclaimer, contentRight - margin)
    if (cursorY + lines.length * 10 > pageHeight - 42) {
      doc.addPage()
      cursorY = drawHeader()
    }
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(75, 85, 99)
    doc.text(lines, margin, cursorY)
  }

  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(75, 85, 99)
    doc.text(`${copy.page} ${page} ${copy.of} ${pageCount}`, pageWidth / 2, pageHeight - 20, { align: 'center' })
    doc.text('StockWise', margin, pageHeight - 20)
    doc.text(model.context.baseCurrency, contentRight, pageHeight - 20, { align: 'right' })
  }

  return doc
}

export async function exportFinancePdf(model: FinanceExportModel) {
  const doc = await buildFinancePdf(model)
  const filename = `${sanitizeFinanceFilename(model.filename.replace(/\.pdf$/i, '')) || 'StockWise_Finance'}.pdf`
  doc.save(filename)
}

export async function printFinanceReport(model: FinanceExportModel) {
  const popup = window.open('', '_blank')
  if (!popup) {
    throw new Error('finance_export_print_window_blocked')
  }
  popup.opener = null

  try {
    const doc = await buildFinancePdf(model)
    const blob = doc.output('blob')
    const url = URL.createObjectURL(blob)
    popup.location.replace(url)
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000)
  } catch (error) {
    popup.close()
    throw error
  }
}
