import type { Locale } from './i18n'
import type { PaymentReceipt } from './operatorSale'
import { formatMoneyBase } from './currency'

export type ReceiptPaper = '58mm' | '80mm' | 'a4'

const escapeHtml = (value: unknown) => String(value ?? '')
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&#039;')

const text = {
  en: {
    title: 'Non-fiscal receipt', proof: 'Proof of payment', customer: 'Customer', walkIn: 'Walk-in / cash customer',
    date: 'Payment date', cashier: 'Cashier', method: 'Payment method', destination: 'Destination', amount: 'Amount received',
    balance: 'Remaining balance', order: 'Sales Order', invoice: 'Sales Invoice', description: 'Description', qty: 'Qty',
    price: 'Unit price', subtotal: 'Subtotal', taxAmount: 'Tax', total: 'Total', tax: 'Tax was not applied to this non-fiscal sale.', generated: 'Generated by StockWise', cash: 'Cash', bank: 'Bank',
  },
  pt: {
    title: 'Recibo não fiscal', proof: 'Comprovativo de pagamento', customer: 'Cliente', walkIn: 'Cliente a dinheiro / balcão',
    date: 'Data do pagamento', cashier: 'Operador', method: 'Método de pagamento', destination: 'Destino', amount: 'Valor recebido',
    balance: 'Saldo remanescente', order: 'Ordem de Venda', invoice: 'Fatura de Venda', description: 'Descrição', qty: 'Qtd.',
    price: 'Preço unitário', subtotal: 'Subtotal', taxAmount: 'Imposto', total: 'Total', tax: 'Não foi aplicado imposto a esta venda não fiscal.', generated: 'Gerado pelo StockWise', cash: 'Dinheiro', bank: 'Banco',
  },
} as const

function snapshotValue(snapshot: Record<string, unknown>, ...keys: string[]) {
  for (const key of keys) {
    const value = snapshot[key]
    if (typeof value === 'string' && value.trim()) return value.trim()
  }
  return ''
}

export function receiptHtml(receipt: PaymentReceipt, locale: Locale, paper: ReceiptPaper = '80mm') {
  const copy = text[locale]
  const company = receipt.company_identity_snapshot || {}
  const customer = receipt.customer_snapshot || {}
  const refs = receipt.document_references || {}
  const destination = receipt.destination_snapshot || {}
  const companyName = snapshotValue(company, 'trade_name', 'legal_name', 'name') || 'StockWise'
  const legalName = snapshotValue(company, 'legal_name')
  const logo = snapshotValue(company, 'logo_url')
  const address = [snapshotValue(company, 'address_line1'), snapshotValue(company, 'address_line2'), snapshotValue(company, 'city'), snapshotValue(company, 'state')].filter(Boolean).join(', ')
  const contact = [snapshotValue(company, 'phone'), snapshotValue(company, 'email')].filter(Boolean).join(' · ')
  const customerName = snapshotValue(customer, 'name', 'display_name', 'legal_name') || copy.walkIn
  const width = paper === '58mm' ? '58mm' : paper === '80mm' ? '80mm' : '190mm'
  const lineRows = (receipt.line_evidence || []).map((line) => `<tr><td>${escapeHtml(line.description)}</td><td class="num">${escapeHtml(line.quantity)}</td><td class="num">${escapeHtml(formatMoneyBase(Number(line.unit_price || 0), receipt.currency_code, locale === 'pt' ? 'pt-MZ' : 'en-MZ'))}</td><td class="num">${escapeHtml(formatMoneyBase(Number(line.total || 0), receipt.currency_code, locale === 'pt' ? 'pt-MZ' : 'en-MZ'))}</td></tr>`).join('')
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><title>${escapeHtml(receipt.receipt_reference)}</title><style>
  @page{size:${paper === 'a4' ? 'A4' : width} auto;margin:${paper === 'a4' ? '14mm' : '4mm'}}*{box-sizing:border-box}body{margin:0;background:#fff;color:#111827;font:12px/1.45 Inter,Arial,sans-serif}.receipt{width:${width};max-width:100%;margin:0 auto;padding:${paper === 'a4' ? '10mm' : '2mm'}}.center{text-align:center}.logo{max-width:42mm;max-height:18mm;object-fit:contain}.brand{font-size:18px;font-weight:800}.muted{color:#4b5563}.rule{border-top:1px dashed #64748b;margin:10px 0}.title{font-size:16px;font-weight:800;text-transform:uppercase}.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 12px}.label{font-size:10px;text-transform:uppercase;color:#6b7280}.value{font-weight:650;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{padding:5px 3px;border-bottom:1px solid #e5e7eb;text-align:left}.num{text-align:right}.totals{margin-left:auto;max-width:90mm}.total-row{display:flex;justify-content:space-between;gap:12px;padding:4px 0}.grand{font-size:15px;font-weight:800}.footer{margin-top:12px;text-align:center;font-size:10px;color:#4b5563}@media print{.receipt{box-shadow:none}}
  </style></head><body><main class="receipt">
  <header class="center">${logo ? `<img class="logo" src="${escapeHtml(logo)}" alt="">` : ''}<div class="brand">${escapeHtml(companyName)}</div>${legalName && legalName !== companyName ? `<div>${escapeHtml(legalName)}</div>` : ''}${snapshotValue(company, 'tax_id') ? `<div>NUIT: ${escapeHtml(snapshotValue(company, 'tax_id'))}</div>` : ''}${address ? `<div class="muted">${escapeHtml(address)}</div>` : ''}${contact ? `<div class="muted">${escapeHtml(contact)}</div>` : ''}<div class="rule"></div><div class="title">${receipt.non_fiscal ? copy.title : copy.proof}</div><div>${copy.proof}</div><div class="value">${escapeHtml(receipt.receipt_reference)}</div></header>
  <div class="rule"></div><section class="grid"><div><div class="label">${copy.date}</div><div class="value">${escapeHtml(new Date(receipt.payment_at).toLocaleString(locale === 'pt' ? 'pt-MZ' : 'en-MZ'))}</div></div><div><div class="label">${copy.customer}</div><div class="value">${escapeHtml(customerName)}</div></div>${refs.sales_order ? `<div><div class="label">${copy.order}</div><div class="value">${escapeHtml(refs.sales_order)}</div></div>` : ''}${refs.sales_invoice ? `<div><div class="label">${copy.invoice}</div><div class="value">${escapeHtml(refs.sales_invoice)}</div></div>` : ''}<div><div class="label">${copy.method}</div><div class="value">${receipt.payment_method === 'bank' ? copy.bank : copy.cash}</div></div><div><div class="label">${copy.destination}</div><div class="value">${escapeHtml(snapshotValue(destination, 'name', 'label') || (receipt.payment_method === 'bank' ? copy.bank : copy.cash))}</div></div></section>
  ${lineRows ? `<div class="rule"></div><table><thead><tr><th>${copy.description}</th><th class="num">${copy.qty}</th><th class="num">${copy.price}</th><th class="num">${copy.total}</th></tr></thead><tbody>${lineRows}</tbody></table>` : ''}
  <div class="rule"></div><section class="totals"><div class="total-row grand"><span>${copy.amount}</span><span>${escapeHtml(formatMoneyBase(receipt.amount_received, receipt.currency_code, locale === 'pt' ? 'pt-MZ' : 'en-MZ'))}</span></div><div class="total-row"><span>${copy.balance}</span><span>${escapeHtml(formatMoneyBase(receipt.remaining_balance, receipt.currency_code, locale === 'pt' ? 'pt-MZ' : 'en-MZ'))}</span></div></section>${receipt.non_fiscal ? `<p class="center muted">${copy.tax}</p>` : ''}<footer class="footer">${snapshotValue(company, 'print_footer_note') ? `<div>${escapeHtml(snapshotValue(company, 'print_footer_note'))}</div>` : ''}<div>${copy.generated}</div></footer>
  </main></body></html>`
}

export function printReceipt(receipt: PaymentReceipt, locale: Locale, paper: ReceiptPaper = '80mm') {
  const popup = window.open('', '_blank', 'noopener,noreferrer,width=520,height=760')
  if (!popup) throw new Error(locale === 'pt' ? 'Permita janelas pop-up para imprimir o recibo.' : 'Allow pop-ups to print the receipt.')
  popup.document.open()
  popup.document.write(receiptHtml(receipt, locale, paper))
  popup.document.close()
  popup.addEventListener('load', () => { popup.focus(); popup.print() }, { once: true })
}

export async function saveReceiptPdf(receipt: PaymentReceipt, locale: Locale) {
  const { default: jsPDF } = await import('jspdf')
  const copy = text[locale]
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const company = receipt.company_identity_snapshot || {}
  const customer = receipt.customer_snapshot || {}
  const refs = receipt.document_references || {}
  const destination = receipt.destination_snapshot || {}
  const companyName = snapshotValue(company, 'trade_name', 'legal_name', 'name') || 'StockWise'
  const legalName = snapshotValue(company, 'legal_name')
  const address = [snapshotValue(company, 'address_line1'), snapshotValue(company, 'address_line2'), snapshotValue(company, 'city'), snapshotValue(company, 'state')].filter(Boolean).join(', ')
  const contact = [snapshotValue(company, 'phone'), snapshotValue(company, 'email')].filter(Boolean).join(' · ')
  const customerName = snapshotValue(customer, 'name', 'display_name', 'legal_name') || copy.walkIn
  const moneyLocale = locale === 'pt' ? 'pt-MZ' : 'en-MZ'
  const lines = receipt.line_evidence || []
  const subtotal = lines.reduce((sum, line) => sum + Number(line.subtotal || 0), 0)
  const tax = lines.reduce((sum, line) => sum + Number(line.tax || 0), 0)
  let y = 18
  const write = (value: string, size = 10, bold = false, gap = 6) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal'); doc.setFontSize(size)
    const wrapped = doc.splitTextToSize(value, 182) as string[]
    doc.text(wrapped, 14, y); y += wrapped.length * gap
  }
  write(companyName, 18, true, 7)
  if (legalName && legalName !== companyName) write(legalName)
  if (snapshotValue(company, 'tax_id')) write(`NUIT: ${snapshotValue(company, 'tax_id')}`)
  if (address) write(address)
  if (contact) write(contact)
  y += 2; write(receipt.non_fiscal ? copy.title : copy.proof, 14, true, 7)
  write(`${copy.proof}: ${receipt.receipt_reference}`, 10, true)
  write(`${copy.date}: ${new Date(receipt.payment_at).toLocaleString(moneyLocale)}`)
  write(`${copy.customer}: ${customerName}`)
  if (refs.sales_order) write(`${copy.order}: ${String(refs.sales_order)}`)
  if (refs.sales_invoice) write(`${copy.invoice}: ${String(refs.sales_invoice)}`)
  write(`${copy.method}: ${receipt.payment_method === 'bank' ? copy.bank : copy.cash}`)
  write(`${copy.destination}: ${snapshotValue(destination, 'name', 'label') || (receipt.payment_method === 'bank' ? copy.bank : copy.cash)}`)
  y += 2; doc.setFont('helvetica', 'bold'); doc.setFontSize(9)
  doc.text(copy.description, 14, y); doc.text(copy.qty, 112, y, { align: 'right' }); doc.text(copy.price, 150, y, { align: 'right' }); doc.text(copy.total, 196, y, { align: 'right' }); y += 5
  doc.setFont('helvetica', 'normal')
  for (const line of lines) {
    const description = doc.splitTextToSize(String(line.description || ''), 88) as string[]
    doc.text(description, 14, y); doc.text(String(line.quantity ?? ''), 112, y, { align: 'right' })
    doc.text(formatMoneyBase(Number(line.unit_price || 0), receipt.currency_code, moneyLocale), 150, y, { align: 'right' })
    doc.text(formatMoneyBase(Number(line.total || 0), receipt.currency_code, moneyLocale), 196, y, { align: 'right' })
    y += Math.max(6, description.length * 5)
  }
  y += 2
  write(`${copy.subtotal}: ${formatMoneyBase(subtotal, receipt.currency_code, moneyLocale)}`)
  write(`${copy.taxAmount}: ${formatMoneyBase(tax, receipt.currency_code, moneyLocale)}`)
  write(`${copy.amount}: ${formatMoneyBase(receipt.amount_received, receipt.currency_code, moneyLocale)}`, 11, true)
  write(`${copy.balance}: ${formatMoneyBase(receipt.remaining_balance, receipt.currency_code, moneyLocale)}`)
  if (receipt.non_fiscal) write(copy.tax)
  const footer = snapshotValue(company, 'print_footer_note')
  if (footer) doc.text(doc.splitTextToSize(footer, 182), 14, 278)
  doc.setFontSize(9); doc.text(copy.generated, 14, 285)
  doc.save(`${receipt.receipt_reference}.pdf`)
}
