
[functions.schema-snapshot]
enabled = true
verify_jwt = false
import_map = "./functions/schema-snapshot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/schema-snapshot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/schema-snapshot/*.html" ]

[functions.ai-ops]
enabled = true
verify_jwt = false
import_map = "./functions/ai-ops/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-ops/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-ops/*.html" ]

[functions.schema-snapshot-cron]
enabled = true
verify_jwt = false
import_map = "./functions/schema-snapshot-cron/deno.json"
# Supported file extensions: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/schema-snapshot-cron/index.ts"
# static_files = [ "./functions/schema-snapshot-cron/*.html" ]

[functions.mailer-invite]
enabled = true
verify_jwt = false
entrypoint = "./functions/mailer-invite/index.ts"
