import { STOCKWISE_EMAIL_BRAND, type EmailBrand } from "./emailBrand.ts";
import type { EmailLanguage } from "./emailMoney.ts";

export const escapeEmailHtml = (value: unknown) => String(value ?? "")
  .replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;").replaceAll("'", "&#039;");

export function renderEmailLayout(input: {
  language: EmailLanguage;
  brand: EmailBrand;
  heading: string;
  intro: string;
  summary: Array<{ label: string; value: string }>;
  actionLabel?: string;
  actionUrl?: string;
  body?: string;
  qa?: boolean;
}) {
  const qaCopy = input.language === "pt"
    ? "Teste de email do StockWise — nenhuma ação é necessária."
    : "StockWise email test — no action is required.";
  const fallback = input.language === "pt" ? "Se o botão não funcionar, copie esta ligação:" : "If the button does not work, copy this link:";
  const contact = [input.brand.contactEmail, input.brand.contactPhone].filter(Boolean).join(" · ");
  const logo = input.brand.logoUrl ? `<img src="${escapeEmailHtml(input.brand.logoUrl)}" alt="" style="display:block;max-width:180px;max-height:64px;width:auto;height:auto;margin-bottom:16px">` : "";
  const summary = input.summary.map((row) => `<tr><td style="padding:8px 0;color:#64748b">${escapeEmailHtml(row.label)}</td><td style="padding:8px 0;text-align:right;font-weight:700;color:#172B4D">${escapeEmailHtml(row.value)}</td></tr>`).join("");
  const action = input.actionUrl && input.actionLabel ? `<div style="margin:24px 0"><a href="${escapeEmailHtml(input.actionUrl)}" style="display:inline-block;padding:12px 18px;border-radius:10px;background:${STOCKWISE_EMAIL_BRAND.accent};color:#fff;text-decoration:none;font-weight:700">${escapeEmailHtml(input.actionLabel)}</a></div><div style="font-size:12px;color:#64748b">${fallback}<br><span style="word-break:break-all">${escapeEmailHtml(input.actionUrl)}</span></div>` : "";
  return `<!doctype html><html lang="${input.language}"><body style="margin:0;background:#f1f5f9;padding:24px;font-family:Inter,Segoe UI,Arial,sans-serif;color:#172B4D"><main style="max-width:680px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden"><header style="padding:26px 30px;background:#f8fafc;border-bottom:3px solid ${STOCKWISE_EMAIL_BRAND.accent}">${logo}<div style="font-size:13px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:${STOCKWISE_EMAIL_BRAND.accent}">${escapeEmailHtml(input.brand.companyName || STOCKWISE_EMAIL_BRAND.name)}</div><h1 style="font-size:26px;line-height:1.25;margin:10px 0 0">${escapeEmailHtml(input.heading)}</h1></header>${input.qa ? `<div style="padding:12px 30px;background:#fef3c7;color:#78350f;font-weight:800">${qaCopy}</div>` : ""}<section style="padding:26px 30px"><p style="font-size:16px;line-height:1.7">${escapeEmailHtml(input.intro)}</p>${input.body ? `<p style="font-size:14px;line-height:1.7;color:#334155">${escapeEmailHtml(input.body)}</p>` : ""}<table role="presentation" style="width:100%;margin-top:18px;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0">${summary}</table>${action}</section><footer style="padding:18px 30px;background:#f8fafc;color:#64748b;font-size:12px;line-height:1.6">${contact ? `${escapeEmailHtml(contact)}<br>` : ""}${escapeEmailHtml(input.language === "pt" ? "Gerado pelo StockWise" : "Generated by StockWise")}</footer></main></body></html>`;
}
