import { renderEmailLayout, type EmailDetailSection, type EmailSemanticVariant } from "./emailLayout.ts";
import type { EmailBrand } from "./emailBrand.ts";
import { formatEmailMoney, type EmailLanguage } from "./emailMoney.ts";

export const EMAIL_TEMPLATE_KEYS = [
  "due_reminder_sales_order", "due_reminder_sales_invoice", "daily_digest", "member_invite", "report_ready",
  "company_access_expiry", "company_access_purge", "company_access_activation",
] as const;
export type EmailTemplateKey = typeof EMAIL_TEMPLATE_KEYS[number];
export type CompanyRole = "OWNER" | "ADMIN" | "MANAGER" | "OPERATOR" | "VIEWER";

type BrandedInput<K extends EmailTemplateKey> = { templateKey: K; brand: EmailBrand; actionUrl?: string };
export type MemberInviteEmailInput = BrandedInput<"member_invite"> & { actionUrl: string; recipientName?: string; inviterName?: string; role: CompanyRole; expiresAt?: string };
export type ReportReadyEmailInput = BrandedInput<"report_ready"> & { actionUrl: string; recipientName?: string; reportName: string; period: string; filters?: string[]; generatedAt?: string };
export type DailyDigestMetrics = { operationalSales: number; knownCogs: number; grossProfit: number | null; grossMargin: number | null; transactions: number; openOrders: number; lowStockItems: number; outOfStockItems: number; missingCostEvidence: number; topProductsServices: string[]; currencyCode: string };
export type DailyDigestEmailInput = BrandedInput<"daily_digest"> & { actionUrl: string; period: string; metrics: DailyDigestMetrics };
export type DueReminderEmailInput<K extends "due_reminder_sales_order" | "due_reminder_sales_invoice"> = BrandedInput<K> & { actionUrl: string; recipientName?: string; documentReference: string; issueDate?: string; dueDate: string; totalAmount?: number; outstandingAmount: number; currencyCode: string; contactName?: string; contactEmail?: string };
export type CompanyAccessExpiryEmailInput = BrandedInput<"company_access_expiry"> & { accessEndsAt: string; currentPlan?: string; supportEmail: string };
export type CompanyAccessPurgeEmailInput = BrandedInput<"company_access_purge"> & { purgeAt: string; accessEndedAt?: string; supportEmail: string };
export type CompanyAccessActivationEmailInput = BrandedInput<"company_access_activation"> & { actionUrl: string; planName: string; activeFrom: string; activeUntil: string; supportEmail: string };

export type EmailTemplateInputMap = {
  member_invite: MemberInviteEmailInput;
  report_ready: ReportReadyEmailInput;
  daily_digest: DailyDigestEmailInput;
  due_reminder_sales_order: DueReminderEmailInput<"due_reminder_sales_order">;
  due_reminder_sales_invoice: DueReminderEmailInput<"due_reminder_sales_invoice">;
  company_access_expiry: CompanyAccessExpiryEmailInput;
  company_access_purge: CompanyAccessPurgeEmailInput;
  company_access_activation: CompanyAccessActivationEmailInput;
};
export type EmailTemplateInput = EmailTemplateInputMap[EmailTemplateKey];
export type RenderedEmail = { templateKey: EmailTemplateKey; templateVersion: number; language: EmailLanguage; semanticVariant: EmailSemanticVariant; scenarioLabel?: string; subject: string; html: string; text: string };
export type EmailTemplateDefinition<K extends EmailTemplateKey> = { key: K; version: number; supportedLanguages: readonly EmailLanguage[]; semanticVariant: EmailSemanticVariant; requiredFields: readonly string[]; render: (language: EmailLanguage, input: EmailTemplateInputMap[K], qa?: boolean) => RenderedEmail };

const versions: Record<EmailTemplateKey, number> = { member_invite: 2, report_ready: 3, daily_digest: 2, due_reminder_sales_order: 3, due_reminder_sales_invoice: 3, company_access_expiry: 2, company_access_purge: 2, company_access_activation: 2 };
const variants: Record<EmailTemplateKey, EmailSemanticVariant> = { member_invite: "informational", report_ready: "informational", daily_digest: "standard", due_reminder_sales_order: "warning", due_reminder_sales_invoice: "warning", company_access_expiry: "warning", company_access_purge: "destructive", company_access_activation: "success" };

function roleName(role: CompanyRole, language: EmailLanguage) {
  const names: Record<CompanyRole, [string, string]> = { OWNER: ["Owner", "Proprietário"], ADMIN: ["Administrator", "Administrador"], MANAGER: ["Manager", "Gestor"], OPERATOR: ["Operator", "Operador"], VIEWER: ["Viewer", "Leitor"] };
  return names[role][language === "pt" ? 1 : 0];
}
function validateActionUrl(actionUrl?: string) {
  if (!actionUrl) return;
  const url = new URL(actionUrl);
  const allowed = ["https://stockwiseapp.com", "https://www.stockwiseapp.com", "https://app.stockwise.co.mz"];
  if (!allowed.includes(url.origin)) throw new Error("email_action_url_not_allowed");
}
function unavailable(pt: boolean) { return pt ? "Indisponível" : "Unavailable"; }
function textOutput(language: EmailLanguage, heading: string, intro: string, body: string | undefined, sections: EmailDetailSection[], notice: string | undefined, actionLabel: string | undefined, actionUrl: string | undefined, brand: EmailBrand, qa: boolean) {
  const pt = language === "pt";
  return [qa ? (pt ? "TEST EMAIL — Este é um email de teste do StockWise. Não é necessária qualquer acção." : "TEST EMAIL — This is a StockWise test email. No action is required.") : "", heading, intro, body, ...sections.flatMap((section) => [section.title, ...section.rows.map((row) => `${row.label}: ${row.value}`)]), notice, actionLabel && actionUrl ? `${actionLabel}: ${actionUrl}` : "", "StockWise", pt ? "Um produto da WiseCore Technologies" : "A WiseCore Technologies product", brand.contactEmail || ""].filter(Boolean).join("\n\n");
}
function result(key: EmailTemplateKey, language: EmailLanguage, input: EmailTemplateInput, qa: boolean, copy: { subject: string; heading: string; intro: string; body?: string; notice?: string; actionLabel?: string; sections: EmailDetailSection[] }): RenderedEmail {
  validateActionUrl(input.actionUrl);
  const subject = `${qa ? "[StockWise QA] " : ""}${copy.subject}`;
  const html = renderEmailLayout({ language, brand: input.brand, heading: copy.heading, intro: copy.intro, body: copy.body, notice: copy.notice, sections: copy.sections, actionLabel: copy.actionLabel, actionUrl: input.actionUrl, qa, variant: variants[key] });
  return { templateKey: key, templateVersion: versions[key], language, semanticVariant: variants[key], subject, html, text: textOutput(language, copy.heading, copy.intro, copy.body, copy.sections, copy.notice, copy.actionLabel, input.actionUrl, input.brand, qa) };
}

function renderMember(language: EmailLanguage, input: MemberInviteEmailInput, qa = false) {
  const pt = language === "pt"; const role = roleName(input.role, language); const inviter = input.inviterName || (pt ? "A equipa" : "The team");
  return result("member_invite", language, input, qa, { subject: pt ? `Foi convidado para entrar na ${input.brand.companyName} no StockWise` : `You have been invited to join ${input.brand.companyName} on StockWise`, heading: pt ? `Entre na ${input.brand.companyName} no StockWise` : `Join ${input.brand.companyName} on StockWise`, intro: pt ? `${inviter} convidou-o para entrar na ${input.brand.companyName} como ${role}.` : `${inviter} invited you to join ${input.brand.companyName} as ${role}.`, body: pt ? "O StockWise ajuda a equipa a gerir stock, vendas, compras e operações diárias num único espaço." : "StockWise helps the team manage stock, sales, purchasing and day-to-day operations in one workspace.", notice: pt ? "Aceite este convite apenas se reconhecer a empresa e a pessoa que o convidou. O StockWise nunca lhe pedirá a palavra-passe por email." : "Only accept this invitation if you recognise the company and the person who invited you. StockWise will never ask for your password by email.", actionLabel: pt ? "Aceitar convite" : "Accept invitation", sections: [{ rows: [{ label: pt ? "Empresa" : "Company", value: input.brand.companyName }, { label: pt ? "Função" : "Role", value: role }, ...(input.inviterName ? [{ label: pt ? "Convidado por" : "Invited by", value: input.inviterName }] : []), ...(input.expiresAt ? [{ label: pt ? "Convite válido até" : "Invitation expires", value: input.expiresAt }] : [])] }] });
}
function renderReport(language: EmailLanguage, input: ReportReadyEmailInput, qa = false) { const pt = language === "pt"; return result("report_ready", language, input, qa, { subject: pt ? `O relatório ${input.reportName} está disponível` : `Your ${input.reportName} report is ready`, heading: pt ? "O seu relatório está disponível" : "Your report is ready", intro: pt ? `O relatório ${input.reportName}, referente ao período ${input.period}, está pronto para consulta.` : `The ${input.reportName} report for ${input.period} is ready to review.`, body: pt ? "O relatório utiliza os filtros seleccionados no momento da geração. Abra-o no StockWise para consultar todos os detalhes." : "The report uses the filters selected when it was generated. Open it in StockWise to review the complete details.", actionLabel: pt ? "Ver relatório" : "View report", sections: [{ rows: [{ label: pt ? "Relatório" : "Report", value: input.reportName }, { label: pt ? "Período" : "Period", value: input.period }, ...(input.filters?.length ? [{ label: pt ? "Filtros" : "Filters", value: input.filters.join(" · ") }] : []), ...(input.generatedAt ? [{ label: pt ? "Gerado em" : "Generated", value: input.generatedAt }] : [])] }] }); }
function renderDigest(language: EmailLanguage, input: DailyDigestEmailInput, qa = false) { const pt = language === "pt"; const m = input.metrics; const money = (value: number) => formatEmailMoney(value, m.currencyCode, language); const missing = m.grossProfit == null || m.grossMargin == null || m.missingCostEvidence > 0; return result("daily_digest", language, input, qa, { subject: pt ? `Resumo operacional — ${input.period}` : `Operational digest — ${input.period}`, heading: pt ? "Resumo operacional" : "Operational digest", intro: pt ? `Visão geral das operações de ${input.period}.` : `Operational overview for ${input.period}.`, body: pt ? "Consulte o desempenho, as excepções que exigem atenção e a principal actividade do período." : "Review performance, exceptions requiring attention, and the period's top activity.", notice: missing ? (pt ? "Algumas vendas não têm evidência de custo completa. Conclua os registos de custeio antes de utilizar o lucro bruto para tomada de decisão." : "Some sales are missing cost evidence. Complete the costing records before relying on gross profit.") : undefined, actionLabel: pt ? "Abrir painel" : "Open dashboard", sections: [{ title: pt ? "Desempenho" : "Performance", emphasis: "metrics", rows: [{ label: pt ? "Vendas operacionais" : "Operational sales", value: money(m.operationalSales) }, { label: pt ? "Custo das vendas" : "COGS", value: money(m.knownCogs) }, { label: pt ? "Lucro bruto" : "Gross profit", value: m.grossProfit == null ? unavailable(pt) : money(m.grossProfit) }, { label: pt ? "Margem bruta" : "Gross margin", value: m.grossMargin == null ? unavailable(pt) : `${m.grossMargin.toFixed(1)}%` }, { label: pt ? "Transacções" : "Transactions", value: String(m.transactions) }] }, { title: pt ? "Atenção necessária" : "Attention required", rows: [{ label: pt ? "Ordens abertas" : "Open orders", value: String(m.openOrders) }, { label: pt ? "Itens com stock baixo" : "Low-stock items", value: String(m.lowStockItems) }, { label: pt ? "Itens sem stock" : "Out-of-stock items", value: String(m.outOfStockItems) }, { label: pt ? "Evidência de custo em falta" : "Missing cost evidence", value: String(m.missingCostEvidence) }] }, { title: pt ? "Principal actividade" : "Top activity", rows: [{ label: pt ? "Principais produtos/serviços" : "Top products/services", value: m.topProductsServices.length ? m.topProductsServices.join(", ") : unavailable(pt) }] }] }); }
function renderReminder(language: EmailLanguage, input: DueReminderEmailInput<"due_reminder_sales_order"> | DueReminderEmailInput<"due_reminder_sales_invoice">, qa = false) { const key = input.templateKey; const pt = language === "pt"; const invoice = key === "due_reminder_sales_invoice"; const amount = formatEmailMoney(input.outstandingAmount, input.currencyCode, language); const document = invoice ? (pt ? "Fatura" : "Invoice") : (pt ? "Ordem de Venda" : "Sales Order"); return result(key, language, input, qa, { subject: pt ? `Lembrete de pagamento da ${document} ${input.documentReference}` : `Payment reminder for ${document} ${input.documentReference}`, heading: invoice ? (pt ? "Lembrete de pagamento da fatura" : "Invoice payment reminder") : (pt ? "Lembrete de pagamento" : "Payment reminder"), intro: invoice ? (pt ? `A Fatura ${input.documentReference} tem o valor de ${amount} em aberto, com vencimento em ${input.dueDate}.` : `Invoice ${input.documentReference} has an outstanding amount of ${amount}, due on ${input.dueDate}.`) : (pt ? `Recordamos que a Ordem de Venda ${input.documentReference} tem o valor de ${amount} em aberto, com vencimento em ${input.dueDate}.` : `This is a reminder that Sales Order ${input.documentReference} has an outstanding amount of ${amount} due on ${input.dueDate}.`), body: invoice ? (pt ? "Solicitamos que efectue o pagamento de acordo com os dados acordados. Caso o pagamento já tenha sido realizado, envie o comprovativo ou ignore este lembrete." : "Please arrange payment using the agreed payment details. If payment has already been made, send the payment confirmation or disregard this reminder.") : (pt ? "Consulte os detalhes da ordem no StockWise. Caso o pagamento já tenha sido acordado, não é necessária qualquer acção adicional." : "Please review the order details in StockWise. If payment has already been arranged, no further action is required."), actionLabel: invoice ? (pt ? "Ver fatura" : "View invoice") : (pt ? "Ver Ordem de Venda" : "View Sales Order"), sections: [{ rows: [{ label: document, value: input.documentReference }, ...(input.issueDate ? [{ label: pt ? "Data de emissão" : "Issue date", value: input.issueDate }] : []), { label: pt ? "Data de vencimento" : "Due date", value: input.dueDate }, ...(input.totalAmount != null ? [{ label: pt ? "Valor total" : "Total amount", value: formatEmailMoney(input.totalAmount, input.currencyCode, language) }] : []), { label: pt ? "Valor em aberto" : "Outstanding amount", value: amount }] }] }); }
function renderExpiry(language: EmailLanguage, input: CompanyAccessExpiryEmailInput, qa = false) { const pt = language === "pt"; return result("company_access_expiry", language, input, qa, { subject: pt ? `O acesso da ${input.brand.companyName} ao StockWise termina em ${input.accessEndsAt}` : `StockWise access for ${input.brand.companyName} ends on ${input.accessEndsAt}`, heading: pt ? "O seu acesso ao StockWise está a terminar" : "Your StockWise access is ending", intro: pt ? `O acesso da ${input.brand.companyName} está programado para terminar em ${input.accessEndsAt}.` : `Access for ${input.brand.companyName} is scheduled to end on ${input.accessEndsAt}.`, body: pt ? "Após esta data, os espaços da empresa poderão ficar indisponíveis. A activação paga e a renovação são tratadas manualmente; o StockWise não efectua cobranças automáticas." : "After this date, company workspaces may become unavailable. Paid activation and renewal are handled manually; StockWise will not charge you automatically.", actionLabel: input.actionUrl ? (pt ? "Contactar o StockWise" : "Contact StockWise") : undefined, sections: [{ rows: [...(input.currentPlan ? [{ label: pt ? "Plano" : "Plan", value: input.currentPlan }] : []), { label: pt ? "Fim do acesso" : "Access ends", value: input.accessEndsAt }] }] }); }
function renderPurge(language: EmailLanguage, input: CompanyAccessPurgeEmailInput, qa = false) { const pt = language === "pt"; return result("company_access_purge", language, input, qa, { subject: pt ? "Acção necessária: dados da empresa programados para eliminação" : "Action required: company data scheduled for deletion", heading: pt ? "Aviso de eliminação dos dados da empresa" : "Company data deletion warning", intro: pt ? `Os dados operacionais da ${input.brand.companyName} estão programados para eliminação em ${input.purgeAt}.` : `Operational data for ${input.brand.companyName} is scheduled for deletion on ${input.purgeAt}.`, body: pt ? "Depois da eliminação, os registos operacionais afectados não poderão ser recuperados através da aplicação. As credenciais de autenticação são geridas separadamente e não são eliminadas por este processo." : "After deletion, the affected operational records cannot be restored through the application. Authentication credentials are managed separately and are not deleted through this process.", actionLabel: input.actionUrl ? (pt ? "Contactar o StockWise" : "Contact StockWise") : undefined, sections: [{ emphasis: "warning", rows: [...(input.accessEndedAt ? [{ label: pt ? "Acesso terminou em" : "Access ended", value: input.accessEndedAt }] : []), { label: pt ? "Eliminação programada" : "Scheduled deletion", value: input.purgeAt }] }] }); }
function renderActivation(language: EmailLanguage, input: CompanyAccessActivationEmailInput, qa = false) { const pt = language === "pt"; return result("company_access_activation", language, input, qa, { subject: pt ? `Acesso ao StockWise activado para ${input.brand.companyName}` : `StockWise access activated for ${input.brand.companyName}`, heading: pt ? "O seu acesso ao StockWise está activo" : "Your StockWise access is active", intro: pt ? `O plano ${input.planName} da ${input.brand.companyName} está activo de ${input.activeFrom} até ${input.activeUntil}.` : `The ${input.planName} plan for ${input.brand.companyName} is active from ${input.activeFrom} until ${input.activeUntil}.`, body: pt ? "Este acesso foi activado manualmente após a confirmação do pagamento. Não activa cobrança automática nem renovação automática." : "This access was activated manually after payment confirmation. It does not enable automatic billing or automatic renewal.", actionLabel: pt ? "Abrir o StockWise" : "Open StockWise", sections: [{ rows: [{ label: pt ? "Plano" : "Plan", value: input.planName }, { label: pt ? "Activo desde" : "Active from", value: input.activeFrom }, { label: pt ? "Activo até" : "Active until", value: input.activeUntil }] }] }); }

export const EMAIL_TEMPLATES = {
  member_invite: { key: "member_invite", version: 2, supportedLanguages: ["en", "pt"], semanticVariant: variants.member_invite, requiredFields: ["brand", "role", "actionUrl"], render: renderMember },
  report_ready: { key: "report_ready", version: 3, supportedLanguages: ["en", "pt"], semanticVariant: variants.report_ready, requiredFields: ["brand", "reportName", "period", "actionUrl"], render: renderReport },
  daily_digest: { key: "daily_digest", version: 2, supportedLanguages: ["en", "pt"], semanticVariant: variants.daily_digest, requiredFields: ["brand", "period", "metrics", "actionUrl"], render: renderDigest },
  due_reminder_sales_order: { key: "due_reminder_sales_order", version: 3, supportedLanguages: ["en", "pt"], semanticVariant: variants.due_reminder_sales_order, requiredFields: ["brand", "documentReference", "dueDate", "outstandingAmount", "currencyCode", "actionUrl"], render: (language: EmailLanguage, input: DueReminderEmailInput<"due_reminder_sales_order">, qa = false) => renderReminder(language, input, qa) },
  due_reminder_sales_invoice: { key: "due_reminder_sales_invoice", version: 3, supportedLanguages: ["en", "pt"], semanticVariant: variants.due_reminder_sales_invoice, requiredFields: ["brand", "documentReference", "dueDate", "outstandingAmount", "currencyCode", "actionUrl"], render: (language: EmailLanguage, input: DueReminderEmailInput<"due_reminder_sales_invoice">, qa = false) => renderReminder(language, input, qa) },
  company_access_expiry: { key: "company_access_expiry", version: 2, supportedLanguages: ["en", "pt"], semanticVariant: variants.company_access_expiry, requiredFields: ["brand", "accessEndsAt", "supportEmail"], render: renderExpiry },
  company_access_purge: { key: "company_access_purge", version: 2, supportedLanguages: ["en", "pt"], semanticVariant: variants.company_access_purge, requiredFields: ["brand", "purgeAt", "supportEmail"], render: renderPurge },
  company_access_activation: { key: "company_access_activation", version: 2, supportedLanguages: ["en", "pt"], semanticVariant: variants.company_access_activation, requiredFields: ["brand", "planName", "activeFrom", "activeUntil", "actionUrl", "supportEmail"], render: renderActivation },
} satisfies { [K in EmailTemplateKey]: EmailTemplateDefinition<K> };

export function renderEmailTemplate<K extends EmailTemplateKey>(key: K, language: EmailLanguage, input: EmailTemplateInputMap[K], qa = false): RenderedEmail {
  if (input.templateKey !== key) throw new Error("email_template_key_mismatch");
  return renderDiscriminatedEmail(language, input, qa);
}

export function renderDiscriminatedEmail(language: EmailLanguage, input: EmailTemplateInput, qa = false): RenderedEmail {
  switch (input.templateKey) {
    case "member_invite": return renderMember(language, input, qa);
    case "report_ready": return renderReport(language, input, qa);
    case "daily_digest": return renderDigest(language, input, qa);
    case "due_reminder_sales_order": return renderReminder(language, input, qa);
    case "due_reminder_sales_invoice": return renderReminder(language, input, qa);
    case "company_access_expiry": return renderExpiry(language, input, qa);
    case "company_access_purge": return renderPurge(language, input, qa);
    case "company_access_activation": return renderActivation(language, input, qa);
  }
}
