import { useEffect, useMemo, useState } from 'react'
import { Bell, CheckCheck, ExternalLink, Filter, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select'
import { useAuth } from '../hooks/useAuth'
import { useOrg } from '../hooks/useOrg'
import { useI18n } from '../lib/i18n'
import { notificationPresentation } from '../lib/notificationPresentation'
import { supabase } from '../lib/supabase'

type Row = { id: string; title: string | null; body: string | null; event_type: string | null; category: string | null; payload: Record<string, unknown>; severity: string | null; action_url: string | null; url: string | null; occurred_at: string | null; created_at: string; read_at: string | null; dismissed_at: string | null }

export default function NotificationsPage() {
  const navigate = useNavigate(); const { lang } = useI18n(); const { companyId } = useOrg(); const { user } = useAuth()
  const [rows,setRows] = useState<Row[]>([]); const [category,setCategory] = useState('all'); const [unread,setUnread] = useState('all'); const [loading,setLoading] = useState(false)
  const copy = lang === 'pt' ? { title:'Notificações',all:'Todas as categorias',unread:'Não lidas',allStates:'Todas',markAll:'Marcar todas como lidas',empty:'Nenhuma notificação corresponde aos filtros.',open:'Abrir',dismiss:'Dispensar' } : { title:'Notifications',all:'All categories',unread:'Unread',allStates:'All',markAll:'Mark all read',empty:'No notifications match these filters.',open:'Open',dismiss:'Dismiss' }
  async function load() { if(!companyId||!user?.id)return; setLoading(true); const {data}=await supabase.from('notifications').select('id,title,body,event_type,category,payload,severity,action_url,url,occurred_at,created_at,read_at,dismissed_at').eq('company_id',companyId).or(`user_id.eq.${user.id},user_id.is.null`).is('dismissed_at',null).order('occurred_at',{ascending:false,nullsFirst:false}).range(0,99); setRows((data||[]) as Row[]); setLoading(false) }
  useEffect(()=>{void load()},[companyId,user?.id])
  const visible=useMemo(()=>rows.filter((row)=>(category==='all'||row.category===category)&&(unread==='all'||!row.read_at)),[category,rows,unread])
  async function mark(id:string, patch:Record<string,string>){await supabase.from('notifications').update(patch).eq('id',id);setRows((current)=>current.map((row)=>row.id===id?{...row,...patch}:row))}
  async function markAll(){if(!companyId)return;const now=new Date().toISOString();await supabase.from('notifications').update({read_at:now}).eq('company_id',companyId).is('read_at',null);setRows((current)=>current.map((row)=>({...row,read_at:row.read_at||now})))}
  const categories=[...new Set(rows.map((row)=>row.category).filter(Boolean))] as string[]
  return <div className="app-page space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="screen-intro"><div className="premium-label">StockWise</div><h1 className="flex items-center gap-2"><Bell className="h-7 w-7" />{copy.title}</h1></div><Button variant="outline" onClick={()=>void markAll()}><CheckCheck className="mr-2 h-4 w-4" />{copy.markAll}</Button></div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Filter className="h-4 w-4" />{copy.title}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{copy.all}</SelectItem>{categories.map((value)=><SelectItem key={value} value={value}>{value.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select><Select value={unread} onValueChange={setUnread}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{copy.allStates}</SelectItem><SelectItem value="unread">{copy.unread}</SelectItem></SelectContent></Select></CardContent></Card><div className="grid gap-3">{!loading&&!visible.length?<Card><CardContent className="p-8 text-center text-muted-foreground">{copy.empty}</CardContent></Card>:visible.map((row)=>{const presentation=notificationPresentation(row,lang);const action=row.action_url||row.url;return <Card key={row.id} className={!row.read_at?'border-primary/35 bg-primary/5':''}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className="rounded-full border px-2 py-1 text-[10px] uppercase">{row.severity||'info'}</span>{!row.read_at?<span className="h-2 w-2 rounded-full bg-primary"/>:null}</div><h2 className="mt-2 font-semibold">{presentation.title}</h2>{presentation.body?<p className="mt-1 text-sm text-muted-foreground">{presentation.body}</p>:null}<div className="mt-2 text-xs text-muted-foreground">{new Date(row.occurred_at||row.created_at).toLocaleString(lang==='pt'?'pt-MZ':'en-MZ')}</div></div><div className="flex shrink-0 flex-wrap gap-2">{!row.read_at?<Button size="sm" variant="outline" onClick={()=>void mark(row.id,{read_at:new Date().toISOString()})}>{copy.unread}</Button>:null}{action?<Button size="sm" onClick={()=>navigate(action)}><ExternalLink className="mr-2 h-4 w-4" />{copy.open}</Button>:null}<Button size="sm" variant="ghost" onClick={()=>void mark(row.id,{dismissed_at:new Date().toISOString()})}><X className="mr-2 h-4 w-4" />{copy.dismiss}</Button></div></CardContent></Card>})}</div></div>
}
