import assert from 'node:assert/strict'
import { readFile, stat } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8')

test('settlement navigation names banks and mobile wallets together', async () => {
  const i18n = await read('src/lib/i18n.tsx')
  assert.match(i18n, /'banks\.title': 'Banks & wallets'/)
  assert.match(i18n, /'nav\.banks': 'Banks & wallets'/)
  assert.match(i18n, /'banks\.title': 'Bancos e carteiras móveis'/)
  assert.match(i18n, /'nav\.banks': 'Bancos e carteiras móveis'/)
})

test('shared date inputs keep native controls aligned with the active theme', async () => {
  const input = await read('src/components/ui/input.tsx')
  assert.match(input, /type === 'date'/)
  assert.match(input, /\[color-scheme:light\]/)
  assert.match(input, /dark:\[color-scheme:dark\]/)
})

test('transactions derive reference filters from actual movement evidence and show production references', async () => {
  const page = await read('src/pages/Transactions.tsx')
  assert.match(page, /const PAGE_SIZE = 50/)
  assert.match(page, /availableRefTypes/)
  assert.match(page, /production_runs/)
  assert.match(page, /reference_no/)
  assert.match(page, /PRODUCTION_RUN_REVERSAL/)
  assert.doesNotMatch(page, /const REF_VALUES =/)
})

test('reports distinguish finalised costing from linked sales and page screen rows at fifty', async () => {
  const reports = await read('src/pages/Reports.tsx')
  assert.match(reports, /const REPORT_PAGE_SIZE = 50/)
  assert.match(reports, /salesEvidence/)
  assert.match(reports, /Finalised costing does not mean sales are linked/)
  assert.match(reports, /No linked Sales Order/)
  assert.match(reports, /loadCompanyLogoImage/)
  assert.match(reports, /Generated by StockWise/)
  assert.match(reports, /rows\.map\(\(row\) => columns\.map/)
  assert.match(reports, /pageRows\.map/)
})

test('company logo helper supports governed deployed logo URLs as well as storage paths', async () => {
  const profile = await read('src/lib/companyProfile.ts')
  assert.match(profile, /\^https\?:\\\/\\\//)
  assert.match(profile, /brand-logos/)
})

test('Leny branding migration is naturally scoped and keeps legal identity untouched', async () => {
  const migration = await read('supabase/migrations/20260902220913_brand_leny_docuras_for_documents.sql')
  assert.match(migration, /c\.name = 'Leny Doçuras'/)
  assert.match(migration, /lower\(cm\.email\) = 'massingasamuel@hotmail\.com'/)
  assert.match(migration, /logo_path = v_logo_url/)
  assert.match(migration, /documents,brand,logoUrl/)
  assert.doesNotMatch(migration, /tax_id\s*=/)
  assert.doesNotMatch(migration, /legal_name\s*=/)
})

test('approved Leny document logo is packaged as a lightweight public asset', async () => {
  const logo = new URL('../../public/brands/leny-docuras.png', import.meta.url)
  const info = await stat(logo)
  assert.ok(info.size > 1000)
  assert.ok(info.size < 100_000)
})